// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_TextArea6;
lv_obj_t * uic_TextArea5;
lv_obj_t * uic_TextArea4;
lv_obj_t * uic_TextArea3;
lv_obj_t * uic_TextArea2;
lv_obj_t * uic_TextArea1;
lv_obj_t * uic_Keyboard2;
lv_obj_t * uic_Label1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_TextArea4 = NULL;
lv_obj_t * ui_TextArea5 = NULL;
lv_obj_t * ui_TextArea6 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -112);
    lv_obj_set_y(ui_Label1, -109);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "text");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Screen1);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, 173);
    lv_obj_set_y(ui_Spinner1, -70);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Keyboard2 = lv_keyboard_create(ui_Screen1);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, 466);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 70);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea1, 44);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea1, -213);
    lv_obj_set_y(ui_TextArea1, -30);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea1, 2);
    lv_textarea_set_placeholder_text(ui_TextArea1, "HH");
    lv_textarea_set_one_line(ui_TextArea1, true);

    ui_TextArea2 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea2, 44);
    lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea2, -162);
    lv_obj_set_y(ui_TextArea2, -30);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea2, 2);
    lv_textarea_set_placeholder_text(ui_TextArea2, "MM");
    lv_textarea_set_one_line(ui_TextArea2, true);

    ui_TextArea3 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea3, 44);
    lv_obj_set_height(ui_TextArea3, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea3, -111);
    lv_obj_set_y(ui_TextArea3, -30);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea3, 2);
    lv_textarea_set_placeholder_text(ui_TextArea3, "SS");
    lv_textarea_set_one_line(ui_TextArea3, true);

    ui_TextArea4 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea4, 44);
    lv_obj_set_height(ui_TextArea4, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea4, -52);
    lv_obj_set_y(ui_TextArea4, -30);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea4, 2);
    lv_textarea_set_placeholder_text(ui_TextArea4, "DD");
    lv_textarea_set_one_line(ui_TextArea4, true);

    ui_TextArea5 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea5, 44);
    lv_obj_set_height(ui_TextArea5, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea5, -2);
    lv_obj_set_y(ui_TextArea5, -30);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea5, 2);
    lv_textarea_set_placeholder_text(ui_TextArea5, "MM");
    lv_textarea_set_one_line(ui_TextArea5, true);

    ui_TextArea6 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea6, 44);
    lv_obj_set_height(ui_TextArea6, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextArea6, 50);
    lv_obj_set_y(ui_TextArea6, -30);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextArea6, 2);
    lv_textarea_set_placeholder_text(ui_TextArea6, "YY");
    lv_textarea_set_one_line(ui_TextArea6, true);

    uic_Label1 = ui_Label1;
    uic_Keyboard2 = ui_Keyboard2;
    uic_TextArea1 = ui_TextArea1;
    uic_TextArea2 = ui_TextArea2;
    uic_TextArea3 = ui_TextArea3;
    uic_TextArea4 = ui_TextArea4;
    uic_TextArea5 = ui_TextArea5;
    uic_TextArea6 = ui_TextArea6;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_Label1 = NULL;
    ui_Label1 = NULL;
    ui_Spinner1 = NULL;
    uic_Keyboard2 = NULL;
    ui_Keyboard2 = NULL;
    uic_TextArea1 = NULL;
    ui_TextArea1 = NULL;
    uic_TextArea2 = NULL;
    ui_TextArea2 = NULL;
    uic_TextArea3 = NULL;
    ui_TextArea3 = NULL;
    uic_TextArea4 = NULL;
    ui_TextArea4 = NULL;
    uic_TextArea5 = NULL;
    ui_TextArea5 = NULL;
    uic_TextArea6 = NULL;
    ui_TextArea6 = NULL;

}
