// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_TextArea6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Label1;
extern lv_obj_t * uic_Keyboard2;
extern lv_obj_t * uic_TextArea1;
extern lv_obj_t * uic_TextArea2;
extern lv_obj_t * uic_TextArea3;
extern lv_obj_t * uic_TextArea4;
extern lv_obj_t * uic_TextArea5;
extern lv_obj_t * uic_TextArea6;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

